Update kernel.yml

diff --git a/.github/workflows/kernel.yml b/.github/workflows/kernel.yml
--- a/.github/workflows/kernel.yml
+++ b/.github/workflows/kernel.yml
@@ -8,11 +8,6 @@ on:
 #  pull_request:
 #    branches: [ master ]
    
-env:
-  repo_url: https://github.com/PixelExperience-Devices/kernel_xiaomi_cepheus
-  repo_branch: twelve
-  build_sh: clang.sh
-  
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -20,15 +15,29 @@ jobs:
     steps:
       - uses: actions/checkout@v2  
  
+      - name: Load Configuration
+        uses: falti/dotenv-action@v0.2.5
+        id: config
+        with:
+          path: config.env
+
+      - name: Check Configuration
+        run: |
+          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
+          required "${{ steps.config.outputs.kernel_name }}" "KERNEL_NAME config"
+          required "${{ steps.config.outputs.build_sh }}" "build_sh config"
+          required "${{ steps.config.outputs.branch_name }}" "BRANCH_NAME config"
+          required "${{ steps.config.outputs.kernel_url }}" "KERNEL_URL config"
+ 
       - name: Git kernel
         run: |
-          git clone $repo_url -b $repo_branch kernel
-
+          git clone "${{ steps.config.outputs.kernel_url }}" -b "${{ steps.config.outputs.branch_name }}" kernel
+          
       - name: make kernel
         run: |
           sudo mv build.sh $GITHUB_WORKSPACE/kernel
           cd $GITHUB_WORKSPACE/kernel
-          bash ./$build_sh
+          bash ./"${{ steps.config.outputs.build_sh }}"
 
       - name: Upload to Release
         uses: ncipollo/release-action@v1
